---
# see https://taskfile.dev/#/
# cspell: ignore buildx
version: "3"
output: group
env: &env
  FORCE_COLOR: "true"
  PRE_COMMIT_COLOR: always
vars:
  HOSTNAME:
    sh: echo ${HOSTNAME:-localhost}
  CNT_NAME: baremetal-playbooks
  VERSION:
    sh: git describe --tags
  CNT_NAME_TAG: "{{.CNT_NAME}}:{{.VERSION}}"
  CNT_NAME_TAG_LATEST: "{{.CNT_NAME}}:latest"
  CNT_ROOT: .
  # Fail if we are not on a tagged commit
  RELEASE_PRECHECK: git describe --tags --exact-match
tasks:
  default:
    desc: Run most commands
    deps:
      - setup
      - lint
      - build
    cmds:
      - echo {{.TASK}}
      - echo Done {{.VERSION}}!
  base:
    desc: Build base image
    sources:
      - base/*
      - .task/.{{.CNT_NAME}}.done
    vars: &base-vars
      VERSION: "latest"
      CNT_NAME: creator-base
      CNT_NAME_TAG: "{{.CNT_NAME}}:{{.VERSION}}"
      CNT_NAME_TAG_LATEST: "{{.CNT_NAME}}:latest"
      CNT_ROOT: base/
      RELEASE_PRECHECK: "true"
    cmds:
      - task: build
        vars: *base-vars
    interactive: true
  clean:
    desc: Clean up all files that not tracked by git
    cmds:
      - git clean -dxf
  setup:
    desc: Install dependencies
    env:
      # used inside test-setup.sh
      OS: "{{OS}}"
      ARCH: "{{ARCH}}"
    cmds:
      - bash ./_build/test-setup.sh
    sources:
      - _build/test-setup.sh
      - Taskfile.yml
    generates:
      - out/log/manifest.yml
    run: once
    interactive: true
  build:
    desc: Build the project
    deps:
      - setup
    env:
      # needed to avoid warning about installing from galaxy
      ANSIBLE_COLLECTIONS_PATHS: collections
    cmds:
      - ansible-galaxy collection install -r _build/requirements.yml -p collections
      - podman manifest exists {{.CNT_NAME_TAG}} && podman manifest rm {{.CNT_NAME_TAG}} || true
      - podman image exists {{.CNT_NAME_TAG}} && podman image rm {{.CNT_NAME_TAG}} || true
      - podman buildx build ${EXTRA_OPTS:---platform=linux/amd64,linux/arm64} --build-arg=CONTAINER_NAME={{.CNT_NAME_TAG}} --load {{.CNT_ROOT}} --manifest {{.CNT_NAME_TAG}}
      # running manifest exists is mandatory as this fails if no manifest is
      # created locally. If this is skipped the inspect might pull the last
      # published manifest instead of using the local one.
      - podman manifest exists {{.CNT_NAME_TAG}}
      # Fail if the manifest does not contain exactly two images
      # Validate image
      - ./_build/validate {{.CNT_NAME_TAG}}
      # Without next step, podman will pull the base image from quay.io instead
      # of using the locally built image when we chain: task base && task build
      - podman tag localhost/{{.CNT_NAME_TAG}} quay.io/ansible/{{.CNT_NAME}}:latest
      - touch .task/.{{.CNT_NAME}}.done
      - echo "=== {{.CNT_NAME_TAG}} is ready! ==="
    sources:
      - Taskfile.yml
      - base/*
      - _build/*
      - Containerfile
    generates:
      - .task/.{{.CNT_NAME}}.done
    interactive: true
  exec:
    desc: Open a container shell
    deps:
      - build
    cmds:
      - podman run --rm -it {{.CNT_NAME_TAG}} /bin/bash
    sources:
      - Taskfile.yml
    interactive: true
  lint:
    desc: Lint the project
    deps:
      - setup
    cmds:
      - python3 -m pre_commit run -a
      - _build/dirty.sh
    silent: true
  pr:
    desc: Opens a pull request using gh
    deps:
      - lint
    cmds:
      - gh pr create
    interactive: true
  release:
    desc: Publish containers to all public registries (used by CI)
    cmds:
      - task: build
        vars: *env
      - "{{.RELEASE_PRECHECK}}"
      - podman manifest push {{.CNT_NAME_TAG}} quay.io/ansible/{{.CNT_NAME_TAG}}
      - podman manifest push {{.CNT_NAME_TAG}} quay.io/ansible/{{.CNT_NAME_TAG_LATEST}}
      - podman manifest push {{.CNT_NAME_TAG}} ghcr.io/ansible/{{.CNT_NAME_TAG}}
      - podman manifest push {{.CNT_NAME_TAG}} ghcr.io/ansible/{{.CNT_NAME_TAG_LATEST}}
    interactive: true
  release-base:
    desc: Publish creator-base container (used by CI)
    vars: *base-vars
    cmds:
      - task: base
        vars: *base-vars
      - "{{.RELEASE_PRECHECK}}"
      - podman manifest push {{.CNT_NAME_TAG}} quay.io/ansible/{{.CNT_NAME_TAG}}
      - podman manifest push {{.CNT_NAME_TAG}} quay.io/ansible/{{.CNT_NAME_TAG_LATEST}}
      - podman manifest push {{.CNT_NAME_TAG}} ghcr.io/ansible/{{.CNT_NAME_TAG}}
      - podman manifest push {{.CNT_NAME_TAG}} ghcr.io/ansible/{{.CNT_NAME_TAG_LATEST}}
    interactive: true
