---
- name: Copy variables file and apply variables
  hosts: github_servers
  gather_facts: no  # No need to gather facts

  vars:
    variables_file: "vars/pipeline-variables.yaml"

  tasks:
    - name: Copy variables file to remote server
      ansible.builtin.copy:
        src: "{{ variables_file }}"
        dest: "/tmp/config.yml"
      register: copy_result

    - name: Ensure the copied file has the correct permissions
      ansible.builtin.file:
        path: "/tmp/config.yml"
        mode: '0644'
      when: copy_result.changed