---
- name: Generate and copy SSH keys
  hosts: github_servers
  gather_facts: false

  tasks:
    - name: Check if SSH key exists
      stat:
        path: "{{ ssh_key_path }}/{{ ssh_key_file }}"
      delegate_to: "{{ inventory_hostname }}"

    - name: copy ssh_public_key variable in the ~/.ssh/{{ ssh_key_file }}.pub locally
      ansible.builtin.copy:
        content: "{{ ssh_public_key }}"
        dest: "~/.ssh/{{ ssh_key_file }}.pub"
      delegate_to: localhost
    

    - name: create ssh_private_key in the ~/.ssh/{{ ssh_key_file }} locally
      ansible.builtin.copy:
        content: "{{ ssh_private_key }}"
        dest: "~/.ssh/{{ ssh_key_file }}"
      delegate_to: localhost

    - name: Copy SSH keys to the server
      ansible.builtin.copy:
          src: "~/.ssh/{{ ssh_key_file }}.pub"
          dest: "{{ ssh_key_path }}/{{ ssh_key_file }}.pub"
          mode: 0600
      delegate_to: "{{ inventory_hostname }}" 

    - name: Copy SSH private key to the server
      ansible.builtin.copy:
          src: "~/.ssh/{{ ssh_key_file }}"
          dest: "{{ ssh_key_path }}/{{ ssh_key_file }}"
          mode: 0600
      delegate_to: "{{ inventory_hostname }}"

    - name: Add public key to authorized_keys
      ansible.builtin.lineinfile:
        path: "{{ ssh_key_path }}/authorized_keys"
        line: "{{ lookup('file', ssh_key_path + '/' + ssh_key_file + '.pub') }}"
        create: yes
      become: true
      delegate_to: "{{ inventory_hostname }}"
