name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: [ubuntu-22.04]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Containerfile
        tags: quay.io/username/baremetal-playbooks:latest

    - name: Validate devfile.yaml
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/clients/odo/latest/odo-linux-amd64
        chmod +x odo-linux-amd64
        sudo mv odo-linux-amd64 /usr/local/bin/odo
    - name: Analyze devfile.yaml
      run: |
        odo analyze  -o json
        odo init --devfile ./devfile.yaml
    - name: Push Docker image to Quay.io
      env:
        QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
        QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      run: |
        docker login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io
        docker push quay.io/${{ secrets.QUAY_USERNAME }}/baremetal-playbooks:latest
