name: Equinix Metal baremetal Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      local-vault:
        description: 'Local Vault Configuration'
        required: false
        default: ''
        type: choice
        options:
          - 'option1'
          - 'option2'
      use-emoji:
        type: boolean
        description: 'Include 🎉🤣 emojis'
      environment:
        type: environment

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip jq
          pip3 install -r requirements.txt

      - name: Set Up HCP CLI
        if: contains(github.event.inputs.args, '--load-from-vault')
        run: |
          curl -fsSL https://cli.replicated.com/install.sh | sh
          hcp profile init --vault-secrets

      - name: Set Executable Permissions
        run: chmod +x bootstrap.sh

      - name: Set Executable Permissions for baremetal.sh
        run: chmod +x baremetal.sh

      - name: Run baremetal.sh Script
        env:
          HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
          HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
          USE_VAULT: ${{ secrets.USE_VAULT }}
          SSH_PUBLIC_KEY: ${{ secrets.SSH_PUBLIC_KEY }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KCLI_PIPELINES_GITHUB_TOKEN: ${{ secrets.KCLI_PIPELINES_GITHUB_TOKEN }}
          OCP_AI_SVC_PIPELINES_GITHUB_TOKEN: ${{ secrets.OCP_AI_SVC_PIPELINES_GITHUB_TOKEN }}
          NEW_HOST: ${{ github.event.inputs.local-vault.NEW_HOST }}
          NEW_USERNAME: ${{ github.event.inputs.local-vault.NEW_USERNAME }}
          NEW_DOMAIN: ${{ github.event.inputs.local-vault.NEW_DOMAIN }}
          NEW_FORWARDER: ${{ github.event.inputs.local-vault.NEW_FORWARDER }}
          FREEIPA_SERVER_FQDN: ${{ github.event.inputs.local-vault.FREEIPA_SERVER_FQDN }}
          FREEIPA_SERVER_DOMAIN: ${{ github.event.inputs.local-vault.FREEIPA_SERVER_DOMAIN }}
          USE_EMOJI: ${{ github.event.inputs.use-emoji }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          # Add other necessary environment variables here
        run: ./baremetal.sh
